# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('youtubeadl', '0003_videoinstance_viewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique id for this audio across the AudioLibrary', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('d', 'downloaded'), ('n', 'not downloaded')], default='n', help_text='audio avaibility', max_length=1)),
                ('audio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='youtubeadl.Audio')),
                ('listener', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
