# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeadl', '0004_audioinstance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio_length',
            new_name='audio_logo',
        ),
    ]
